//
// Created by yonggyulee on 2024. 8. 2.
//

#ifndef PREVIEW_CONFIG_H_
#define PREVIEW_CONFIG_H_

#ifdef PREVIEW_CMAKE_CONFIG

// Use compiler/STL configuration generated by CMake
#include "preview/cmake_config.h"

#else

// Use heuristic configuration
#include "preview/cmake_config.h.in"

#endif

#endif // PREVIEW_CONFIG_H_
