//
// Created by yonggyulee on 2023/12/23.
//

#ifndef PREVIEW_ITERATOR_H_
#define PREVIEW_ITERATOR_H_

#include "preview/__iterator/detail/iter_concept.h"

#include "preview/__iterator/iterator_traits/forward_declare.h"
#include "preview/__iterator/iterator_traits.h"
#include "preview/__iterator/iterator_traits/legacy_bidirectional_iterator.h"
#include "preview/__iterator/iterator_traits/legacy_forward_iterator.h"
#include "preview/__iterator/iterator_traits/legacy_input_iterator.h"
#include "preview/__iterator/iterator_traits/legacy_iterator.h"
#include "preview/__iterator/iterator_traits/legacy_random_access_iterator.h"

#include "preview/__iterator/advance.h"
#include "preview/__iterator/basic_const_iterator.h"
#include "preview/__iterator/bidirectional_iterator.h"
#include "preview/__iterator/common_iterator.h"
#include "preview/__iterator/contiguous_iterator.h"
#include "preview/__iterator/counted_iterator.h"
#include "preview/__iterator/data.h"
#include "preview/__iterator/default_sentinel_t.h"
#include "preview/__iterator/empty.h"
#include "preview/__iterator/forward_iterator.h"
#include "preview/__iterator/incrementable.h"
#include "preview/__iterator/incrementable_traits.h"
#include "preview/__iterator/indirect_binary_predicate.h"
#include "preview/__iterator/indirect_equivalence_relation.h"
#include "preview/__iterator/indirect_result_t.h"
#include "preview/__iterator/indirect_strict_weak_order.h"
#include "preview/__iterator/indirect_unary_predicate.h"
#include "preview/__iterator/indirectly_comparable.h"
#include "preview/__iterator/indirectly_copyable.h"
#include "preview/__iterator/indirectly_copyable_storable.h"
#include "preview/__iterator/indirectly_movable.h"
#include "preview/__iterator/indirectly_movable_storable.h"
#include "preview/__iterator/indirectly_readable.h"
#include "preview/__iterator/indirectly_readable_traits.h"
#include "preview/__iterator/indirectly_regular_unary_invocable.h"
#include "preview/__iterator/indirectly_swappable.h"
#include "preview/__iterator/indirectly_unary_invocable.h"
#include "preview/__iterator/indirectly_writable.h"
#include "preview/__iterator/input_iterator.h"
#include "preview/__iterator/input_or_output_iterator.h"
#include "preview/__iterator/iter_common_reference_t.h"
#include "preview/__iterator/iter_const_reference_t.h"
#include "preview/__iterator/iter_difference_t.h"
#include "preview/__iterator/iter_key_t.h"
#include "preview/__iterator/iter_mapped_t.h"
#include "preview/__iterator/iter_move.h"
#include "preview/__iterator/iter_reference_t.h"
#include "preview/__iterator/iter_rvalue_reference_t.h"
#include "preview/__iterator/iter_swap.h"
#include "preview/__iterator/iter_val_t.h"
#include "preview/__iterator/iter_value_t.h"
#include "preview/__iterator/iterator_tag.h"
#include "preview/__iterator/mergeable.h"
#include "preview/__iterator/move_iterator.h"
#include "preview/__iterator/move_sentinel.h"
#include "preview/__iterator/next.h"
#include "preview/__iterator/output_iterator.h"
#include "preview/__iterator/permutable.h"
#include "preview/__iterator/prev.h"
#include "preview/__iterator/projected.h"
#include "preview/__iterator/projected_value_t.h"
#include "preview/__iterator/random_access_iterator.h"
#include "preview/__iterator/range_access.h"
#include "preview/__iterator/reverse_iterator.h"
#include "preview/__iterator/sentinel_for.h"
#include "preview/__iterator/sized_sentinel_for.h"
#include "preview/__iterator/sortable.h"
#include "preview/__iterator/std_common_iterator.h"
#include "preview/__iterator/std_counted_iterator.h"
#include "preview/__iterator/unreachable_sentinel.h"
#include "preview/__iterator/weakly_incrementable.h"

#include "preview/__ranges/begin.h"
#include "preview/__ranges/cbegin.h"
#include "preview/__ranges/cend.h"
#include "preview/__ranges/data.h"
#include "preview/__ranges/empty.h"
#include "preview/__ranges/end.h"
#include "preview/__ranges/size.h"
#include "preview/__ranges/ssize.h"

#endif // PREVIEW_ITERATOR_H_
