//
// Created by yonggyulee on 2024. 10. 20.
//

#ifndef PREVIEW_CONCEPTS_V2_DETAIL_CONFIG_H_
#define PREVIEW_CONCEPTS_V2_DETAIL_CONFIG_H_

#if PREVIEW_CXX_VERSION < 20
#define PREVIEW_USE_LEGACY_CONCEPT
#endif

#define PREVIEW_CONCEPT_LEXICAL_NAMESPACE pc_
#define PREVIEW_CONCEPT_LEXICAL_NAMESPACE_OPEN namespace pc_ {
#define PREVIEW_CONCEPT_LEXICAL_NAMESPACE_CLOSE } // namespace pc_

#endif // PREVIEW_CONCEPTS_V2_DETAIL_CONFIG_H_
